# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/job_scheduler',
                'doc_host': 'https://eandreas.github.io',
                'git_url': 'https://github.com/eandreas/job_scheduler',
                'lib_path': 'job_scheduler'},
  'syms': {'job_scheduler.core': {'job_scheduler.core.foo': ('core.html#foo', 'job_scheduler/core.py')}}}
