# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['KeepLastN', 'BackupRotation']

# %% ../nbs/00_core.ipynb 4
class KeepLastN():
    '''
    
    '''
    def __init__(n, keepList):
        self.n = n
        self.keepList = keepList

# %% ../nbs/00_core.ipynb 5
class BackupRotation():
    '''
    
    '''
    def __init__(self, targetBakupDir, keepLastNDays, keepLastNWeeks, keepLastNMonths, keepLastNYears):
        self.targetBakupDir = targetBakupDir
        self.keepLastNDays = keepLastNDays
        self.keepLastNWeeks = keepLastNWeeks
        self.keepLastNMonths = keepLastNMonths
        self.keepLastNYears = keepLastNYears
